<?php
$title = "Global Server Locations";
$css = "locations";
include 'includes/head.php';
include 'includes/nav.php';
?>

<section class="page-hero text-center">
  <div class="container" data-animate>
    <h1>Global Server Locations</h1>
    <p class="subheadline">EnderBit servers span the globe so your players get the lowest possible latency — wherever they are.</p>
  </div>
</section>

<section class="map-section container">
  <div class="map-container" data-animate style="position: relative; width: 100%; max-width: 1000px; margin: 0 auto; aspect-ratio: 950 / 620;">
    <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-image: url('https://upload.wikimedia.org/wikipedia/commons/8/80/World_map_-_low_resolution.svg'); background-size: cover; background-position: center; opacity: 0.8; filter: invert(1) hue-rotate(180deg) brightness(1.5) contrast(0.8); pointer-events: none;"></div>
    
    <!-- Markers -->
    <!-- NA-West -->
    <div class="map-marker-html" style="position: absolute; left: 17%; top: 35%; transform: translate(-50%, -50%);">
      <div class="pulse-ring-html"></div>
      <div class="pulse-ring-html" style="animation-delay: 1s;"></div>
      <div class="marker-dot"></div>
      <div class="marker-tooltip">NA-West (Los Angeles)</div>
    </div>
    <!-- NA-East -->
    <div class="map-marker-html" style="position: absolute; left: 26%; top: 35%; transform: translate(-50%, -50%);">
      <div class="pulse-ring-html"></div>
      <div class="pulse-ring-html" style="animation-delay: 1s;"></div>
      <div class="marker-dot"></div>
      <div class="marker-tooltip">NA-East (Virginia)</div>
    </div>
    <!-- EU-West -->
    <div class="map-marker-html" style="position: absolute; left: 48%; top: 25%; transform: translate(-50%, -50%);">
      <div class="pulse-ring-html"></div>
      <div class="pulse-ring-html" style="animation-delay: 1s;"></div>
      <div class="marker-dot"></div>
      <div class="marker-tooltip">EU-West (London)</div>
    </div>
    <!-- AU-East -->
    <div class="map-marker-html" style="position: absolute; left: 88%; top: 80%; transform: translate(-50%, -50%);">
      <div class="pulse-ring-html"></div>
      <div class="pulse-ring-html" style="animation-delay: 1s;"></div>
      <div class="marker-dot"></div>
      <div class="marker-tooltip">AU-East (Sydney)</div>
    </div>
  </div>
</section>

<section class="regions-section container">
  <div class="regions-grid" id="regions-grid">
    <!-- Cards generated by JS -->
  </div>
</section>

<section class="chart-section container">
  <h2 class="text-center" data-animate>Your Latency to Each Region</h2>
  <div class="chart-container" data-animate id="latency-chart">
    <!-- Chart generated by JS -->
  </div>
</section>

<script src="/js/locations.js?v=<?php echo filemtime(__DIR__ . '/js/locations.js'); ?>"></script>
<?php include 'includes/footer.php'; ?>