<?php
$title = "Global Server Locations";
$css = "locations";
include 'includes/head.php';
include 'includes/nav.php';
?>

<section class="page-hero text-center">
  <div class="container" data-animate>
    <h1>Global Server Locations</h1>
    <p class="subheadline">EnderBit servers span the globe so your players get the lowest possible latency — wherever they are.</p>
  </div>
</section>

<section class="map-section container">
  <div class="map-container" data-animate>
    <svg viewBox="0 0 1000 500" class="world-map-svg">
      <!-- Simplified World Map Paths -->
      <path d="M 100 100 Q 150 50 200 100 T 300 150 Q 350 200 300 250 T 200 300 Q 150 350 100 300 T 50 200 Q 0 150 50 100 Z" fill="#0d1117" stroke="#1e2a3a" stroke-width="2"/>
      <path d="M 400 100 Q 450 50 500 100 T 600 150 Q 650 200 600 250 T 500 300 Q 450 350 400 300 T 350 200 Q 300 150 350 100 Z" fill="#0d1117" stroke="#1e2a3a" stroke-width="2"/>
      <path d="M 700 100 Q 750 50 800 100 T 900 150 Q 950 200 900 250 T 800 300 Q 750 350 700 300 T 650 200 Q 600 150 650 100 Z" fill="#0d1117" stroke="#1e2a3a" stroke-width="2"/>
      <path d="M 750 350 Q 800 300 850 350 T 900 400 Q 850 450 800 400 T 750 350 Z" fill="#0d1117" stroke="#1e2a3a" stroke-width="2"/>
      
      <!-- Markers -->
      <!-- NA-West -->
      <g class="map-marker" transform="translate(150, 180)">
        <circle cx="0" cy="0" r="12" class="pulse-ring" />
        <circle cx="0" cy="0" r="24" class="pulse-ring" style="animation-delay: 1s;" />
        <circle cx="0" cy="0" r="4" fill="#2563eb" />
        <title>NA-West (Los Angeles)</title>
      </g>
      <!-- NA-East -->
      <g class="map-marker" transform="translate(250, 170)">
        <circle cx="0" cy="0" r="12" class="pulse-ring" />
        <circle cx="0" cy="0" r="24" class="pulse-ring" style="animation-delay: 1s;" />
        <circle cx="0" cy="0" r="4" fill="#2563eb" />
        <title>NA-East (Virginia)</title>
      </g>
      <!-- EU-West -->
      <g class="map-marker" transform="translate(480, 140)">
        <circle cx="0" cy="0" r="12" class="pulse-ring" />
        <circle cx="0" cy="0" r="24" class="pulse-ring" style="animation-delay: 1s;" />
        <circle cx="0" cy="0" r="4" fill="#2563eb" />
        <title>EU-West (London)</title>
      </g>
      <!-- AU-East -->
      <g class="map-marker" transform="translate(820, 380)">
        <circle cx="0" cy="0" r="12" class="pulse-ring" />
        <circle cx="0" cy="0" r="24" class="pulse-ring" style="animation-delay: 1s;" />
        <circle cx="0" cy="0" r="4" fill="#2563eb" />
        <title>AU-East (Sydney)</title>
      </g>
    </svg>
  </div>
</section>

<section class="regions-section container">
  <div class="regions-grid" id="regions-grid">
    <!-- Cards generated by JS -->
  </div>
</section>

<section class="chart-section container">
  <h2 class="text-center" data-animate>Your Latency to Each Region</h2>
  <div class="chart-container" data-animate id="latency-chart">
    <!-- Chart generated by JS -->
  </div>
</section>

<script src="/js/locations.js"></script>
<?php include 'includes/footer.php'; ?>